default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 6991
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: search_engine_development

test:
  <<: *default
  database: search_engine_test

production:
  <<: *default
  database: search_engine_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
