default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: my_database_user
  password: my_database_password
  socket: /var/run/mysqld/mysqld.sock
  timeout: 5000

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: my_production_database_user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
